spring:
  profiles:
    active: local

  application:
    name: BOOK_BE

  jackson:
    serialization:
      fail-on-empty-beans: false

  sql:
    init:
      mode: always

  external:
    loader:
      enabled: false
      batchSize: 10

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10


kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  search-url: https://dapi.kakao.com/v3/search/book

# Springdoc OpenAPI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/HBD?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100

  external:
    loader:
      enabled: true
      batchSize: 10

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:oracle:thin:@${DB_CONNECTION}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  external:
    loader:
      enabled: false
      batchSize: 10
