spring:
  profiles:
    active: local

  application:
    name: BOOK_BE

  jackson:
    serialization:
      fail-on-empty-beans: false

  sql:
    init:
      mode: always

external:
  cultural-data-loader:
    enabled: false
    batchSize: 100

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  search-url: https://dapi.kakao.com/v3/search/book

national-library:
  url: ${NATIONAL_LIBRARY_API_URL:https://www.nl.go.kr/seoji/SearchApi.do}
  key: ${NATIONAL_LIBRARY_API_KEY}

# Sentry Configuration
sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SPRING_PROFILES_ACTIVE:local}
  server-name: book-be
  traces-sample-rate: 1.0
  debug: false
  enable-request-interceptor: true
  tags:
    service: book-be
    version: 1.0.0

# Springdoc OpenAPI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/HBD?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100
  batch:
    jdbc:
      initialize-schema: embedded

external:
  cultural-data-loader:
    enabled: true
    batchSize: 100

sentry:
  debug: true
  traces-sample-rate: 0.1
  tags:
    service: book-be
    version: 1.0.0
    env: local


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:oracle:thin:@${DB_CONNECTION}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

external:
  cultural-data-loader:
    enabled: false
    batchSize: 100

# Dev 환경 Sentry 설정
sentry:
  debug: false
  traces-sample-rate: 0.5  # 개발 환경에서는 50% 샘플링
  tags:
    service: book-be
    version: 1.0.0
    env: dev
    database: oracle