spring:
  profiles:
    active: local

  application:
    name: BOOK_BE

  jackson:
    serialization:
      fail-on-empty-beans: false

  sql:
    init:
      mode: always

# JWT 설정
jwt:
  secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012345678901234567890}
  access-token-expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME:3600000}  # 1시간 (1000 * 60 * 60)
  refresh-token-expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME:604800000}  # 7일 (1000 * 60 * 60 * 24 * 7)

external:
  cultural-data-loader:
    enabled: false
    batchSize: 100

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  search-url: https://dapi.kakao.com/v3/search/book

national-library:
  url: ${NATIONAL_LIBRARY_API_URL:https://www.nl.go.kr/seoji/SearchApi.do}
  key: ${NATIONAL_LIBRARY_API_KEY}

# Springdoc OpenAPI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs

---
# Local 환경 (Oracle 개발용)
spring:
  config:
    activate:
      on-profile: local
  
  datasource:
    #    url: jdbc:mysql://localhost:3306/HBD?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    username: root
    #    password: password
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: bookapp
    password: password123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      connection-timeout: 5000
  
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQLDialect
        dialect: org.hibernate.dialect.OracleDialect
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100
  
  batch:
    jdbc:
      initialize-schema: embedded

external:
  cultural-data-loader:
    enabled: false
    batchSize: 100

---
# Dev 환경 (운영 Oracle)
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:oracle:thin:@${DB_CONNECTION}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      connection-timeout: 5000
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

external:
  cultural-data-loader:
    enabled: false
    batchSize: 100