package com.hbd.book_be.exception

object ErrorCodes {
    const val MISSING_PUBLISHER_INFO = "MISSING_PUBLISHER_INFO"
    const val MISSING_AUTHOR_INFO = "MISSING_AUTHOR_INFO"
    const val INVALID_EVENT_DATE = "INVALID_EVENT_DATE"
    const val EVENT_ACCESS_DENIED = "EVENT_ACCESS_DENIED"
    const val INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
}